config/routes.rb
Rails.application.routes.draw do


  root to: 'page#index'

  resources :stores  do
    collection { post :import }
  end
  resources :tickets
  resources :vouchers
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard' => "dashboard#index"
  get '/vouchers', to: 'vouchers#index', as: :vouchers_path
  get '/profile', to: 'page#profile', as: :profile
  get '/store-profile', to: 'page#store_profile', as: :store_profile
  get '/user-profile', to: 'page#user_profile', as: :user_profile
  get '/term-and-condition', to: 'page#tnc', as: :tnc
  get '/privacy-policy', to: 'page#privacy_policy', as: :privacy
  get '/how-to-join', to: 'page#howto', as: :howto
  get '/all-store', to: 'page#all_store', as: :all_store
  get '/store-leaderboards', to: 'page#store_leaderboards', as: :store_leaderboards
  get ':voucher_code', to: 'page#rdr', as: :rdr
  get '/detail/:id', to: 'tickets#detail', as: :dtl
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout "admin"

  def index
    @tickets = Ticket.where(status: ["new","onprogress"])
    @stores = Store.all
    @customers = User.where(role: "CRM")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_indx_admin.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3 col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="d-flex align-items-center">
            <div>
              <h3 class="font-light m-b-5"><%= Ticket.where(status: "approve").count %></h3>
              <a href="<%= tickets_path(status: "approve") %>">
              <span class="text-primary">Point Baru</span>
              </a>
            </div>
            <div class="ml-auto">
              <div id="sales3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="d-flex align-items-center">
            <div>
              <h3 class="font-light m-b-5"><%= Ticket.where(status: "approve").sum(:point) %></h3>
              <a href="<%= tickets_path(status: "approve") %>">
              <span class="text-primary">Total Poin</span>
              </a>
            </div>
            <div class="ml-auto">
              <div id="sales3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="d-flex align-items-center">
            <div>
              <h3 class="font-light m-b-5"><%= Ticket.where(status: "reject").count %></h3>
              <a href="<%= tickets_path(status: "reject") %>">
              <span class="text-primary">Tranksaksi Reject</span>
              </a>
            </div>
            <div class="ml-auto">
              <div id="sales3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="d-flex align-items-center">
            <div>
              <h3 class="font-light m-b-5"><%= Ticket.all.count %></h3>
              <a href="<%= tickets_path %>">
              <span class="text-primary">Total Redeem</span>
              </a>
            </div>
            <div class="ml-auto">
              <div id="sales3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h4>New Point Request</h4>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th><%= "id".titleize %></th>
                  <th><%= "user".titleize %></th>
                  <th><%= "store".titleize %></th>
                  <th><%= "created_at".titleize %></th>
                  <th><%= "status".titleize %></th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <% @tickets.each do |ticket| %>
                  <tr>
                    <td><%= link_to ticket.id, ticket_path(ticket) %></td>
                    <td><%= ticket.user.name %></td>
                    <td><%= ticket.store.name %></td>
                    <td><%=l ticket.created_at %></td>
                    <td><%= ticket.status %></td>
                    <td>
                      <a href="<%= edit_ticket_path(ticket) %>" class="btn btn-primary">Validate Now</a>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4>Store Leaderboard</h4>
          <div class="table-responsive">
            <table class="table table-striped tbl-str">
              <thead>
                <tr>
                  <th><%= "id".titleize %></th>
                  <th><%= "name".titleize %></th>
                  <th>Address</th>
                    <th>Total Poin</th>
                  <th>Total Tranksaksi</th>
                </tr>
              </thead>
              <tbody>
                <% @stores.each do |store| %>
                <tr>
                  <td><%= link_to store.id, store_path(store) %></td>
                  <td><%= store.name %></td>
                  <td><%= store.address %></td>
                  <td><%= store.tickets.sum(:point) %></td>
                    <td><%= store.tickets.where(status: "approve").count %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4>Customer Leaderboard</h4>
          <div class="table-responsive">
            <table class="table table-striped tbl-csr">
              <thead>
                <tr>
                  <th><%= "id".titleize %></th>
                  <th><%= "name".titleize %></th>
                  <th>Total Poin</th>
                  <th>Total Tranksaksi</th>
                </tr>
              </thead>
              <tbody>
                <% @customers.each do |user| %>
                <tr>
                  <td><%= link_to user.id, user_path(user) %></td>
                  <td><%= user.name %></td>
                  <td><%= user.tickets.sum(:point) %></td>
                  <td><%= user.tickets.where(status: "approve").count %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
      </div>
    </div>




  </div>


</div>


<script type="text/javascript">
  $(document).ready(function() {
    $('.tbl-str').DataTable({
      "order": [[ 2, "desc" ]]
    });
  } );
</script>

<script type="text/javascript">
  $(document).ready(function() {
    $('.tbl-csr').DataTable({
      "order": [[ 2, "desc" ]]
    });
  } );
</script>

app/views/dashboard/index.html.erb
<% if current_user.is_admin? %>
  <%= render 'indx_admin' %>
  <% else %>
  <%= render 'indx_str' %>
<% end %>