config/routes.rb
Rails.application.routes.draw do


  root to: 'page#index'

  resources :stores  do
    collection { post :import }
  end
  resources :tickets
  resources :vouchers
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard' => "dashboard#index"
  get '/vouchers', to: 'vouchers#index', as: :vouchers_path
  get '/profile', to: 'page#profile', as: :profile
  get '/store-profile', to: 'page#store_profile', as: :store_profile
  get '/user-profile', to: 'page#user_profile', as: :user_profile
  get '/term-and-condition', to: 'page#tnc', as: :tnc
  get '/privacy-policy', to: 'page#privacy_policy', as: :privacy
  get '/how-to-join', to: 'page#howto', as: :howto
  get '/all-store', to: 'page#all_store', as: :all_store
  get '/store-leaderboards', to: 'page#store_leaderboards', as: :store_leaderboards
  get ':voucher_code', to: 'page#rdr', as: :rdr
  get '/detail/:id', to: 'tickets#detail', as: :dtl
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tickets
  has_one :store

    validates :email, uniqueness: true, presence: true
    validates :ktp, presence: true
    validates :phone_number, length: {minimum: 6, maximum: 15}, uniqueness: true, allow_blank: true
    before_validation :normalize_phone_number

  mount_uploader :ktp, ImageUploader

  Roles = {
    admin: 'ADM',
    customer: 'CRM',
    store: "STR",
  }.freeze

  def is_admin?
    self.role == Roles[:admin]
  end

  def is_customer?
    self.role == Roles[:customer]
  end

  def is_store?
    self.role == Roles[:store]
  end

  def normalize_phone_number
    if self.phone_number.present?
      number = self.phone_number.scan(/\d/).join('')

      if number[0..1] == '08'
        self.phone_number = "#{number}"
        prefix  = self.phone_number
      elsif number[0..2] == '+62'
        self.phone_number = "0#{number[3..number.length]}"
        prefix  = self.phone_number
      elsif number[0..1] == '62'
        self.phone_number = "0#{number[2..number.length]}"
        prefix = self.phone_number
      else
        self.phone_number = "08#{number}"
        prefix  = self.phone_number
      end

      prefix  = prefix.scan(/\d/).join('')

      if prefix[0..3] == ["0831","0832","0832","0838"]
        self.provider = "AX10"
      elsif ["0856","0857","0858","0815","0816","0855","0814"].include?(prefix[0..3])
        self.provider = "I10"
      elsif  ["0881","0882","0883","0884","0885","0886","0887","0888","0889"].include?(prefix[0..3])
        self.provider = "SM10"
      elsif  ["0811","0812","0813","0821","0822","0823","0852","0853","0851"].include?(prefix[0..3])
        self.provider = "S10"
      elsif ["0896","0897","0898","0899","0895"].include?(prefix[0..3])
        self.provider = "T10"
      elsif ["0817","0818","0819","0859","0877","0878"].include?(prefix[0..3])
        self.provider = "X10"
      else
        self.provider = "UNKNOWN"
      end
    end
  end

  def self.send_pulsa(code, phoneNumber, ticket)
    url = "https://tripay.co.id/api/v2/transaksi/pembelian"
    @send_pulsa = Faraday.post('https://tripay.co.id/api/v2/transaksi/pembelian') do |req|
      req.headers['Authorization'] = "Bearer XffCVv829TfJU3jm0RSZg6k81w2C4ymK"
      req.headers['Content-Type'] = 'application/json'
      req.body = { inquiry: 'I', code: code, phone: phoneNumber, pin: '2156', api_trxid:  ticket}.to_json
    end
    logger.info @send_pulsa.body
  end

  def self.send_notif(user)
    mg_client = Mailgun::Client.new 'd95979082ed1a94540dc0ba29d3a3d88-2a9a428a-0451ae4f'

    # Define your message parameters
    message_params =  { from: 'no-reply@siapaktiflagi.com',
                        to:   "#{user.email}",
                        subject: 'Selamat Bergabung di Program #siapaktiflagi',
                        template: 'thanks_message',
                        "v:name":"#{user.name}"
                      }

    # Send your message through the client
    mg_client.send_message 'siapaktiflagi.com', message_params
  end

  def self.notif_admin
    mg_client = Mailgun::Client.new 'd95979082ed1a94540dc0ba29d3a3d88-2a9a428a-0451ae4f'

    # Define your message parameters
    message_params =  { from: 'no-reply@siapaktiflagi.com',
                        to:   "project@seva-advertising.com",
                        subject: 'Ada Poin Baru masuk',
                        template: 'notif'
                      }

    # Send your message through the client
    mg_client.send_message 'siapaktiflagi.com', message_params
  end

  def self.notif_approve(user)
    mg_client = Mailgun::Client.new 'd95979082ed1a94540dc0ba29d3a3d88-2a9a428a-0451ae4f'

    # Define your message parameters
    message_params =  { from: 'no-reply@siapaktiflagi.com',
                        to:   "#{user.email}",
                        subject: 'Pulsa Sudah dikirimkan',
                        template: 'success',
                        "v:name":"#{user.name}",
                        "v:phone_number":"#{user.phone_number}"
                      }

    # Send your message through the client
    mg_client.send_message 'siapaktiflagi.com', message_params
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  layout "admin"
  before_action :authenticate_user!
  # GET /users or /users.json
  def index
    if params[:client].present?
      @users =  User.where(role: "CRM")
    else
      @users =  User.all
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :phone_number, :address)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    <h3 class="text-warning"><i class="fa fa-exclamation-triangle"></i> <%= pluralize(@user.errors.count, "error") %> </h3>
    <p>prohibited this user from being saved:</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>
<div class="row">

  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="row">

          <div class="col">
            <div class="form-group">
              <%=  f.label :name, :class => 'control-label' %>
              <%=  f.text_field :name, :class => 'form-control' %>
              <%= f.error_span(:name) %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :email, :class => 'control-label' %> <small><i>Required</i></small>
              <%= f.text_field :email, :class => 'form-control', required: true %>
              <%=f.error_span(:email) %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :role, :class => 'control-label' %> <small><i>Required</i></small>
              <%= f.select :role, User::Roles.map {|r| [r.last.to_s, r.last.to_s] }, {:include_blank => '- Choose -'}, :class => 'form-control',:required => true %>
              <%=f.error_span(:role) %>
            </div>
          </div>
        </div>




        <div class="row">
          <div class="col">
            <%= f.label :password, :class => 'control-label' %> <small><i>Required</i></small>
            <%= f.password_field :password, :class => 'form-control', required:true %>
            <%=f.error_span(:password) %>
          </div>
          <div class="col">
            <%= f.label :password_confirmation, :class => 'control-label' %> <small><i>Required</i></small>
            <%= f.password_field :password_confirmation, :class => 'form-control', required:true %>
            <%=f.error_span(:password_confirmation) %>
          </div>
        </div>
        <div class="row">
          <div class="col text-center">
            <div class="form-group mt-3">
              <%= f.submit nil, :class => 'btn btn-success' %>
              <%= link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-light' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => "Contact" %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= stores_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")),new_user_path,:class => 'btn btn-success mb-2'%>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th><%= model_class.human_attribute_name(:id) %></th>
                  <th><%= model_class.human_attribute_name(:name) %></th>
                  <th><%= model_class.human_attribute_name(:email) %></th>
                  <th><%= model_class.human_attribute_name(:phone_number) %></th>
                  <th> Point</th>
                  <th><%=t '.actions', :default => t("helpers.actions") %></th>
                </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                <tr>
                  <td><%= link_to user.id, user_path(user) %></td>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.phone_number %></td>
                  <td><%= Ticket.where(user_id: user.id).count %></td>
                  <td>
                    <a href="<%= user_profile_path(id: user.id) %>">detail</a>
                    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_user_path(user), :class => 'btn btn-default btn-xs' %>
                    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    user_path(user),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-xs btn-danger' %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.table').DataTable({
      "order": [[ 0, "desc" ]]
    });
  } );
</script>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => "Contact" %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= dashboard_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= stores_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone_number) %>:</strong></dt>
  <dd><%= @user.phone_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @user.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:voucher_code) %>:</strong></dt>
  <dd><%= @user.voucher_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
  <dd><%= @user.role %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>