config/routes.rb
Rails.application.routes.draw do


  root to: 'page#index'

  resources :stores  do
    collection { post :import }
  end
  resources :tickets
  resources :vouchers
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard' => "dashboard#index"
  get '/vouchers', to: 'vouchers#index', as: :vouchers_path
  get '/profile', to: 'page#profile', as: :profile
  get '/store-profile', to: 'page#store_profile', as: :store_profile
  get '/user-profile', to: 'page#user_profile', as: :user_profile
  get '/term-and-condition', to: 'page#tnc', as: :tnc
  get '/privacy-policy', to: 'page#privacy_policy', as: :privacy
  get '/how-to-join', to: 'page#howto', as: :howto
  get '/all-store', to: 'page#all_store', as: :all_store
  get '/store-leaderboards', to: 'page#store_leaderboards', as: :store_leaderboards
  get ':voucher_code', to: 'page#rdr', as: :rdr
  get '/detail/:id', to: 'tickets#detail', as: :dtl
end

app/views/page/all_store.html.erb
<section class="bg-main pt-5 d-flex align-items-center" style="min-height:100vh;">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class= "position-relative ">
          <div class="img-heading">
            <img src="<%= asset_url('bg-heading.png') %>" alt="" class="">
          </div>
          <div class="position-relative" style="z-index:89">
            <h2 class="heading" style="color:#E51959">Toko yang Berpartisipasi</h2>
          </div>
        </div>
      </div>
      <div class="col-md-12">



        <div class="mt-4">
          <h3>DANDAN</h3>
          <div class="card">
            <div class="card-body">
              <div class="table-responsive c">
                <table class="table table-bordered border-dark">

                  <thead>
                    <tr>
                      <th>Nama Toko</th>
                      <th>Kota</th>
                      <th>Alamat</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% Store.where("name LIKE ?", "%Dan+Dan%").each do |x| %>
                    <tr>
                      <td><%= x.name %></td>
                      <td><%= x.city %></td>
                      <td><%= x.address %></td>
                    </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="mt-4">
          <h3>WATSONS</h3>

          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered border-dark">
                  <thead>
                    <tr>
                      <th>Nama Toko</th>
                      <th>Kota</th>
                      <th>Alamat</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% Store.where("name LIKE ?", "%WATSONS%").each do |x| %>
                    <tr>
                      <td><%= x.name %></td>
                      <td><%= x.city %></td>
                      <td><%= x.address %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-12">



        <div class="mt-4">
          <h3>VIVA APOTEK</h3>

          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered border-dark">
                  <thead>
                    <tr>
                      <th>Nama Toko</th>
                      <th>Kota</th>
                      <th>Alamat</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% Store.where(id: [1176..1286]).each do |x| %>
                    <tr>
                      <td><%= x.name %></td>
                      <td><%= x.city %></td>
                      <td><%= x.address %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-12">



        <div class="mt-4 mb-5">
          <h3>Apotik</h3>

        <div class="card">
            <div class="card-body">
              <table class="table table-bordered border-dark">

                <thead>
                  <tr>
                    <th>Nama Toko</th>
                    <th>Kota</th>
                    <th>Alamat</th>
                  </tr>
                </thead>
                <tbody>
                  <% Store.where(id: [863..974]).each do |x| %>
                  <tr>
                    <td><%= x.name %></td>
                    <td><%= x.city %></td>
                    <td><%= x.address %></td>
                  </tr>
                  <% end %>
                </tbody>

              </table>
            </div>
        </div>

        </div>




      </div>

    </div>

  </div>
</section>

app/views/page/howto.html.erb
<section id="howto" class="d-none d-md-block position-relative mt-0" >
  <div class="container">
    <div class="text-center position-relative mb-5">
      <div class="img-heading">
        <img src="<%= asset_url('bg-heading.png') %>" alt="" class="">
      </div>
      <div class="position-relative" style="z-index:89">
        <h2 class="heading">Cara Bergabung</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3 text-center">
        <img src="<%= asset_url('hw1.png') %>" alt="" class="w-100">
      </div>
      <div class="col-md-3 text-center">
        <img src="<%= asset_url('hw2.png') %>" alt="" class="w-100">

      </div>
      <div class="col-md-3 text-center">
        <img src="<%= asset_url('hw3.png') %>" alt="" class="w-100">
      </div>
      <div class="col-md-3 text-center">
        <img src="<%= asset_url('hw4.png') %>" alt="" class="w-100">
      </div>
    </div>
  </div>
</section>

<section class="d-md-none position-relative" id="howto" class="d-flex align-items-center justify-content-center " style="margin-top:0">
  <div class="container">
    <div class="text-center position-relative mb-5">
      <div class="img-heading">
        <img src="<%= asset_url('bg-heading.png') %>" alt="" class="">
      </div>
      <div class="position-relative" style="z-index:89">
        <h2 class="heading">Cara Bergabung</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-7  ">
        <img src="<%= asset_url('hw1.png') %>" alt="" class="w-100">
      </div>
    </div>
    <div class="row justify-content-end">
      <div class="col-8  ">
        <img src="<%= asset_url('hw2.png') %>" alt="" class="w-100">
      </div>
    </div>
    <div class="row">
      <div class="col-7  ">
        <img src="<%= asset_url('hw3.png') %>" alt="" class="w-100">
      </div>
    </div>
    <div class="row justify-content-end">
      <div class="col-8  ">
        <img src="<%= asset_url('hw4.png') %>" alt="" class="w-100">
      </div>
    </div>
  </div>
</section>

<section class="bg-main pt-5 ">
  <div class="container">
    <div class="row">
      <div class="col-md-6">

        <div class= "position-relative ">
          <div class="img-heading">
            <img src="<%= asset_url('bg-heading.png') %>" alt="" class="">
          </div>
          <div class="position-relative" style="z-index:89">
            <h2 class="heading" style="color:#E51959">Syarat & Ketentuan</h2>
          </div>
        </div>

        <ol class="py-5">
          <li>Untuk mendapatkan 1 voucher undian customer harus melakukan tranksaksi 2 box produk ifree.</li>
          <li>Setiap customer wajib mengisi data diri, bukti transaksi dan foto prosuk kedalam website.</li>
          <li>Pemenang akan dipilih berdasarkan poin pembelian terbanyak yang bisa dilihat di website www.siapaktiflagi.com.</li>
          <li>Jika ada transaksi yang dianggap tidak valid atau tidak lengkap maka tim admin Ifree berhak menolak data transaksi konsumen yang telah di upload ke website. </li>
          <li>Kuota pulsa 10,000 hanya berlaku untuk 8,000 pembeli pertama. Pembeli selanjutnya hanya bisa mengikuti program poin berhadiah smartphone.</li>
          <li>Program ini tidak berlaku untuk keluarga besar Caplang Group, Pihak Toko yang terlibat, agency dan semua tim yang terkait dalam program campaign ini.</li>
          <li>Periode Program berlaku mulai 1 Juni - 31 Juli.</li>
        </ol>

      </div>
      <div class="col-md-6" style="display: flex;align-items: flex-end;">
        <img src="<%= asset_url('ifree-shop2 1.png') %>" alt="" class="w-100" s>
      </div>
    </div>

  </div>
</section>

app/views/page/index.html.erb
<section style=" " class="bg-main position-relative">

  <div class="d-none d-md-block">
    <img src="<%= asset_url('hero-section.png') %>" alt="" class="w-100">

    <div class="btn-container">
      <div class="container" style="margin-left:20%;">
        <a href="#howto" class="btn btn-main">Ambil Hadiahnya Sekarang!</a>
      </div>
    </div>
  </div>

  <div class="w-100 d-md-none">
    <img src="<%= asset_url('heromobile.png') %>" alt="" class="w-100">
    <div class="btn-container" style="height:0; top:63vh">
      <div class="container" style="text-align: center;">
        <a href="<%= new_user_session_path %>" class="btn btn-main">Ambil Hadiahnya Sekarang!</a>
      </div>
    </div>
  </div>
</section>



<section class="d-none d-md-block position-relative" id="howto" class="d-flex align-items-center justify-content-center ">
  <div class="container">
    <div class="text-center position-relative mb-5">
      <div class="img-heading">
        <img src="<%= asset_url('bg-heading.png') %>" alt="" class="">
      </div>
      <div class="position-relative" style="z-index:89">
        <h2 class="heading">Cara Bergabung</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3 text-center">
        <img src="<%= asset_url('hw1.png') %>" alt="" class="w-100">
      </div>
      <div class="col-md-3 text-center">
        <img src="<%= asset_url('hw2.png') %>" alt="" class="w-100">

      </div>
      <div class="col-md-3 text-center">
        <img src="<%= asset_url('hw3.png') %>" alt="" class="w-100">
      </div>
      <div class="col-md-3 text-center">
        <img src="<%= asset_url('hw4.png') %>" alt="" class="w-100">
      </div>
    </div>
  </div>
</section>

<section class="d-md-none position-relative" id="howto" class="d-flex align-items-center justify-content-center " style="margin-top:0">
  <div class="container">
    <div class="text-center position-relative mb-5">
      <div class="img-heading">
        <img src="<%= asset_url('bg-heading.png') %>" alt="" class="">
      </div>
      <div class="position-relative" style="z-index:89">
        <h2 class="heading">Cara Bergabung</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-7  ">
        <img src="<%= asset_url('hw1.png') %>" alt="" class="w-100">
      </div>
    </div>
    <div class="row justify-content-end">
      <div class="col-8  ">
        <img src="<%= asset_url('hw2.png') %>" alt="" class="w-100">
      </div>
    </div>
    <div class="row">
      <div class="col-7  ">
        <img src="<%= asset_url('hw3.png') %>" alt="" class="w-100">
      </div>
    </div>
    <div class="row justify-content-end">
      <div class="col-8  ">
        <img src="<%= asset_url('hw4.png') %>" alt="" class="w-100">
      </div>
    </div>


  </div>
</section>

<section class="py-5 text-center" style="background:#2A0D4A">
  <div class="container">
      <div class="row align-items-center">
        <div class="col-md-3">

            <img src="<%= asset_url('ifree-girls2.png') %>" alt="" class="w-100">

        </div>
        <div class="col-md-9">
          <h2 style="color:white;" >Untuk Kamu yang sudah belanja minimal 2 produk iFree, kamu dapat melakukan Redem Poin dengan memilih toko tempat kamu belanja dibawah ini:</h2>

          <a href="<%= new_registration_path(User, group: "DANDAN") %>">
            <img src="<%= asset_url('logo-dandan.png') %>" alt="logo dandan" class="m-3" style="width:150px;">
          </a>

          <a href="<%= new_registration_path(User, group: "VIVA") %>">
            <img src="<%= asset_url('logo-viva.png') %>" alt="logo viva" class="m-4" style="width:150px;">
          </a>

          <a href="<%= new_registration_path(User, group: "WATSONS") %>">
            <img src="<%= asset_url('logo-watsons.png') %>" alt="logo viva" class="m-4" style="width:150px;">
          </a>

          <a href="<%= new_registration_path(User, group: "APOTEK") %>" class="m-4 btn btn-main">
            Apotik Lainnya
          </a>

        </div>
      </div>
  </div>
</section>

<section class="bg-main pt-5 ">
  <div class="container">
    <div class="row">
      <div class="col-md-6">

        <div class= "position-relative ">
          <div class="img-heading">
            <img src="<%= asset_url('bg-heading.png') %>" alt="" class="">
          </div>
          <div class="position-relative" style="z-index:89">
            <h2 class="heading" style="color:#E51959">Syarat & Ketentuan Program #siapaktiflagi</h2>
          </div>
        </div>

        <ol class="py-5">
          <li>Untuk mendapatkan 1 poin undian Smartphone Samsung A30 dan gratis pulsa Rp. 10.000,- customer harus melakukan tranksaksi 2 box produk ifree.</li>
          <li>Setiap customer yang mengikuti program ini wajib mengisi data diri, bukti transaksi dan foto produk melalui website www.siapaktiflagi.com atau scan QR code di store yang berpartisipasi.</li>
          <li>10 Pemenang Smartphone  Samsung A30 akan dipilih berdasarkan poin pembelian terbanyak yang bisa dilihat di website www.siapaktiflagi.com.</li>
          <li>Jika ada transaksi yang dianggap tidak valid atau tidak lengkap maka tim admin Ifree berhak menolak data transaksi konsumen yang telah di upload ke website.</li>
          <li>Kuota pulsa 10,000 hanya berlaku untuk 8,000 pembeli pertama. Pembeli selanjutnya hanya bisa mengikuti program poin berhadiah 10 unit Smartphone Samsung A30. </li>
          <li>Program ini tidak berlaku untuk keluarga besar Caplang Group, Pihak Toko yang terlibat, agency dan semua tim yang terkait dalam program campaign ini.</li>
          <li>Periode Program berlaku mulai 1 Juni - 31 Juli 2021.</li>
        </ol>

        <div class="mb-5">
          <a href="<%= all_store_path %>" class="btn btn-main">Lihat Toko yang Berpartisipasi</a>
        </div>

      </div>
      <div class="col-md-6" style="display: flex;align-items: flex-end;">
        <img src="<%= asset_url('ifree-shop2 1.png') %>" alt="" class="w-100" s>
      </div>
    </div>

  </div>
</section>




<section class="py-5 text-light" style="background-color: #E61A58;">
  <div class="container">
    <div class="row align-items-center justify-content-between">
          <div class="col-md-6">
            <div class="row">
              <div class="w-100" style="">
                <video controls class="w-100">
                  <source src="<%= asset_url('video.mp4') %>" type="video/mp4">
                    <source src="<%= asset_url('video.mp4') %>" type="video/ogg">
                      Your browser does not support the video tag.
                    </video>
                  </div>
                  <!-- <div class="col-md-4">
                    <img src="<%= asset_url('ifree-girls2.png') %>" alt="" class="w-100">
                  </div> -->
                </div>
              </div>
              <div class="col-md-6">
                <div class="text-center position-relative mb-5">
                  <div class="img-heading">
                    <img src="<%= asset_url('bg-heading.png') %>" alt="" class="">
                  </div>
                  <div class="position-relative" style="z-index:89">
                    <h2 class="heading">Apa Itu iFree ?</h2>
                  </div>
                </div>
                <div class="mt-3">
                  <h3 style="font-family: Lobster;">iFree, Pad Terapi Hangat</h3>
                  <p>iFree, pad terapi hangat ketika nyeri haid. Dengan proses alami OxyHeat, yang menimbulkan efek hangat sampai dengan 8 jam, efektif membantu mengurangi kram perut dan nyeri haid</p>
                  <p>Tinggal tempel, #siapaktiflagi</p>
                  <h4>Keunggulan iFree</h4>
                  <ol>
                    <li>Inovasi pad terapi hangat pertama di Indonesia Praktis (tinggal tempel)</li>
                    <li>Efektif (meredakan nyaeri haid, karena terapi hangat dapat  mengurangi ketegangan otot perut yang kram) </li>
                    <li>Dengan proses alami OxyHeat, langsung  hangat ketika terkena udara dan hangatnya tahan  sampai dengan 8 jam.</li>
                  </ol>
                  <div class="mt-5">
                    <img src="<%= asset_url('banner-campaign.png') %>" alt="" class="w-100">
                  </div>
                </div>
              </div>


        </div>
      </div>
    </section>

    <section class="bg-main py-5 ">
      <div class="container">
        <div class="text-center position-relative mb-5">
          <div class="img-heading">
            <img src="<%= asset_url('bg-heading.png') %>" alt="" class="">
          </div>
          <div class="position-relative" style="z-index:89">
            <h2 class="heading" style="color:#E51959">Cara Pemakaian</h2>
          </div>
        </div>
        <div class="mt-3">
          <div class="row justify-content-between">
            <div class="col-md-3">
              <img src="<%= asset_url('how-to-1.gif') %>" alt="" class="w-100 mb-3">
              <div class="d-flex">
                <div class="me-3 mt-3">
                  <h3 style="font-family: Lobster;color:#e61a58">1.</h3>
                </div>
                <div class="">
                  <h4>Buka kemasan iFree, pad akan menghangat saat terpapar udara</h4>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <img src="<%= asset_url('how-to-2.gif') %>" alt="" class="w-100 mb-3">
              <div class="d-flex">
                <div class="me-3 mt-3">
                  <h3 style="font-family: Lobster;color:#e61a58">2.</h3>
                </div>
                <div class="">
                  <h4>Lepaskan lapisan perekat pad.</h4>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <img src="<%= asset_url('how-to-3.gif') %>" alt="" class="w-100 mb-3">
              <div class="d-flex">
                <div class="me-3 mt-3">
                  <h3 style="font-family: Lobster;color:#e61a58">3.</h3>
                </div>
                <div class="">
                  <h4>Tempel pad pada bagian kram haid.</h4>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="mt-3">
          <div class="row justify-content-between">
            <div class="col-md-12">
              <img src="<%= asset_url('heat-use.png') %>" alt="" class="w-100">
            </div>

          </div>
        </div>
      </div>
    </section>

    <section class="py-5 text-center" style="background:#2A0D4A">



      <p style="font-family: Lato; font-size: 18px; line-height: 22px; text-align: center;color: #FFFFFF;">Mulai bergabung dan kumpulkan poin kamu <br>
        untuk mendapatkan kesempatan memenangkan Grand Prize</p>

        <a href="<%= new_user_session_path %>" class="btn btn-main">Ambil Hadiahnya Sekarang!</a>

      </section>



      <!-- Modal -->
      <div class="modal fade" id="popupbanner" tabindex="-1" role="dialog" aria-labelledby="popupbannerTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg"  role="document">
          <div class="modal-content">

            <div class="modal-body p-0">
              <img src="<%= asset_url('popupbanner.jpeg') %>" alt="" class="w-100">
            </div>
            <div class="modal-footer justify-content-center">
              <a href="<%= howto_path %>" class="btn btn-main">Ambil Hadiahnya Sekarang!</a>
            </div>
          </div>
        </div>
      </div>

app/views/page/privacy_policy.html.erb
<section style="min-height:50vh; padding:120px 0; background-image:url('https://ifreeindonesia.com/wp-content/themes/ifree/assets/images/bg-form-reg-1.png');background-repeat:no-repeat; background-size:cover;background-position:center;" id="tnc" class="d-flex align-items-center justify-content-center " >
  <div class="container">
    <div class="text-center text-light mb-5">
        <h1>Privacy Policy for Siap Aktif Lagi</h1>
    </div>


<p>At Siap Aktif Lagi, accessible from http://siapaktiflagi.com/, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by Siap Aktif Lagi and how we use it.</p>

<p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>

<h2>Log Files</h2>

<p>Siap Aktif Lagi follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information. Our Privacy Policy was created with the help of the <a href="https://www.privacypolicyonline.com/privacy-policy-generator/">Privacy Policy Generator</a> and the <a href="https://www.generateprivacypolicy.com">Privacy Policy Generator</a>.</p>

<h2>Cookies and Web Beacons</h2>

<p>Like any other website, Siap Aktif Lagi uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>

<p>For more general information on cookies, please read the "What Are Cookies" article on <a href="https://www.privacypolicyonline.com/what-are-cookies/">Cookie Consent website</a>.</p>



<h2>Privacy Policies</h2>

<P>You may consult this list to find the Privacy Policy for each of the advertising partners of Siap Aktif Lagi.</p>

<p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on Siap Aktif Lagi, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>

<p>Note that Siap Aktif Lagi has no access to or control over these cookies that are used by third-party advertisers.</p>

<h2>Third Party Privacy Policies</h2>

<p>Siap Aktif Lagi's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. </p>

<p>You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites. What Are Cookies?</p>

<h2>Children's Information</h2>

<p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>

<p>Siap Aktif Lagi does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>

<h2>Online Privacy Policy Only</h2>

<p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Siap Aktif Lagi. This policy is not applicable to any information collected offline or via channels other than this website.</p>

<h2>Consent</h2>

<p>By using our website, you hereby consent to our Privacy Policy and agree to its Terms and Conditions.</p>

  </div>
</section>

app/views/page/profile.html.erb

<section style="min-height:100vh;" class="d-flex  bg-main">

  <div class="container-fluid">

    <div class=" my-5">

      <div class="row align-items-center justify-content-center">



        <div class="col-md-4">
          <div class="shadow bg-light" style="border-radius: 10px;">
            <div class="px-2 pt-2 text-center pb-2 mb-3" style="border-top-right-radius: 10px;border-top-left-radius: 10px; background:#E61A58">
              <h4 class="text-light mb-0 ">Profile Kamu</h4>
            </div>

            <div class="row">
              <div class="col-6">
                <div class="px-4 pt-2">
                  <div class="mb-2">
                    <p class="mb-0 text-muted" style="font-size:14px; font-weight:900">Nama</p>
                    <p style="font-size:20px; font-weight:900;margin-bottom:0;"><%= current_user.name %></p>
                  </div>
                  <div class="mb-2">
                    <p class="mb-0 text-muted" style="font-size:14px; font-weight:900">Nomor Telepon</p>
                    <p style="font-size:20px; font-weight:900;margin-bottom:0;"><%= current_user.phone_number %></p>
                  </div>
                  <div class="mb-2">
                    <p class="mb-0 text-muted" style="font-size:14px; font-weight:900">Alamat Email</p>
                    <p style="font-size:20px; font-weight:900;margin-bottom:0;"><%= current_user.email %></p>
                  </div>
                </div>
              </div>
              <div class="col-6">
                <div class="px-4 pt-2">
                  <p class="mb-0 text-muted text-center mb-3" style="font-size:14px; font-weight:900">Jumlah Poin Kamu</p>
                  <div class="d-flex align-items-center justify-content-center m-auto" style="height:100px; width:100px;background:#e8406b;border-radius:100%;" >
                    <h3 style="margin:0;color:white"><%= current_user.tickets.count %></h3>
                  </div>
                </div>
              </div>
            </div>

            <div class="px-4 pb-4">
              <hr>
              <p class="mb-0 text-muted mb-3" style="font-size:14px; font-weight:900">Histori Belanja</p>

              <table class="table table-striped table-bordered" style="border-radius:10%  ">
                <tbody>
                  <% Ticket.where(user_id: current_user.id).where(status: "approve").each do |tc| %>
                  <tr>
                    <th><p class="mb-0 text-muted" style="font-size:8px; font-weight:900"><%= tc.created_at %></p>
                    <p style="font-size:14px; font-weight:900;margin-bottom:0;"><%= tc.store.name.titleize rescue "-" %></p></th>
                  </tr>
                    <% end %>
                </tbody>
              </table>

              <div class="mb-4">
                <a href="<%= root_path %>" class="btn btn-main w-100" >Kembali ke Halaman Utama</a>
              </div>

            </div>





          </div>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/page/rdr.html.erb

<section style="min-height:100vh;background:url('https://ifreeindonesia.com/wp-content/themes/ifree/assets/images/bg-form-reg-1.png')%>');background-color:#D0E1EB; padding:80px 0;" class="d-flex align-items-center justify-content-center">

<div class="container">

  <div class=" my-5">
    <div class="shadow p-4 bg-light text-center" style="border-radius: 10px;">
        <h3>Maaf, Kode Voucher Tidak di temukan</h3>
    </div>
  </div>
</div>

</section>

app/views/page/store_leaderboards.html.erb
<section class="bg-main pt-5 d-flex align-items-center" style="min-height:100vh;">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6">

        <div class="card shadow" style="border-radius: 10px;">
          <div class="card-body p-3">



        <div class= "position-relative ">

          <div class="position-relative" style="z-index:89">
            <h2 class="heading" style="color:#E51959">Store Leaderbaords</h2>
          </div>
          <p class="mt-5">
            Berikut toko- toko dengan jumlah poin terbanyak. Tingkat terus poin toko kamu untuk mendapatkan hadiah.
          </p>
        </div>


        <table class="table table-borderless" >
          <thead>
            <tr>
              <th></th>
              <th>Nama Toko</th>
              <th>Total Poin</th>
            </tr>

          </thead>
          <tbody class="border-0">
            <% Store.joins(:tickets).where("tickets.status = ?", "approve" ).uniq.each_with_index do |x,i| %>
            <%# Store.all.order(created_at: :asc).limit(10).each_with_index do |x,i| %>
            <tr class="border-0" >
              <td><p class="rank-number"><%= i + 1 %></p></td>
              <td><p class="rank"><%= x.name  %></p></td>
              <td><p class="rank" ><%=  x.tickets.count  %></p></td>
            </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>


      </div>
      <div class="col-md-6" style="display: flex;align-items: flex-end;">
        <img src="<%= asset_url('ifree-girls2.png') %>" alt="" class="w-100" s>
      </div>
    </div>

  </div>
</section>