config/routes.rb
Rails.application.routes.draw do


  root to: 'page#index'

  resources :stores  do
    collection { post :import }
  end
  resources :tickets
  resources :vouchers
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard' => "dashboard#index"
  get '/vouchers', to: 'vouchers#index', as: :vouchers_path
  get '/profile', to: 'page#profile', as: :profile
  get '/store-profile', to: 'page#store_profile', as: :store_profile
  get '/user-profile', to: 'page#user_profile', as: :user_profile
  get '/term-and-condition', to: 'page#tnc', as: :tnc
  get '/privacy-policy', to: 'page#privacy_policy', as: :privacy
  get '/how-to-join', to: 'page#howto', as: :howto
  get '/all-store', to: 'page#all_store', as: :all_store
  get '/store-leaderboards', to: 'page#store_leaderboards', as: :store_leaderboards
  get ':voucher_code', to: 'page#rdr', as: :rdr
  get '/detail/:id', to: 'tickets#detail', as: :dtl
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>IFREE</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="preloader">
    <div class="lds-ripple">
      <div class="lds-pos"></div>
      <div class="lds-pos"></div>
    </div>
  </div>
  <div id="main-wrapper" data-sidebartype="full">
    <header class="topbar">
      <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header">
          <!-- This is for the sidebar toggle which is visible on mobile only -->
          <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)">
            <i class="ti-menu ti-close"></i>
          </a>
          <!-- ============================================================== -->
          <!-- Logo -->
          <!-- ============================================================== -->
          <div class="navbar-brand">
            <a href="<%= root_path %>" class="logo">
              <!--End Logo icon -->
              <!-- Logo text -->
              <span class="logo-text p-2">
                <!-- dark Logo text -->
                <img src="/assets/user.png" alt="homepage" class="dark-logo" />
                <!-- Light Logo text -->
                <img src="/assets/logo.png" class="light-logo p-3" alt="homepage" style="height:77px" />
              </span>
            </a>
            <a class="sidebartoggler d-none d-md-block" href="javascript:void(0)" data-sidebartype="mini-sidebar">
              <i class="mdi mdi-toggle-switch mdi-toggle-switch-off font-20"></i>
            </a>
          </div>
          <!-- ============================================================== -->
          <!-- End Logo -->
          <!-- ============================================================== -->
          <!-- ============================================================== -->
          <!-- Toggle which is visible on mobile only -->
          <!-- ============================================================== -->
          <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="ti-more"></i>
        </a>
      </div>
      <!-- ============================================================== -->
      <!-- End Logo -->
      <!-- ============================================================== -->
      <div class="navbar-collapse collapse" id="navbarSupportedContent">
        <ul class="navbar-nav float-left mr-auto">
        </ul>
        <ul class="navbar-nav float-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: black;">
              <img src="<%= asset_url('user.png') %>" alt="" class="rounded-circle" width="40">
              <span class="m-l-5 font-medium d-none d-sm-inline-block"><%= current_user.name %> <i class="fa fa-chevron-down"></i></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
              <span class="with-arrow">
                <span class="bg-primary"></span>
              </span>
              <div class="d-flex no-block align-items-center p-3 bg-primary text-white m-b-10">
                <div class="">
                  <img src="<%= asset_url('user.png') %>" alt="" class="rounded-circle" width="60">
                </div>
                <div class="ml-3">
                  <h4 class="mb-0"><%= current_user.name rescue '-' %></h4>
                  <p class="mb-0"><%= current_user.email %></p>
                </div>
              </div>
              <a class="dropdown-item" href="<%= user_path(current_user.id) %>">
                <i class="fa fa-user mr-3 ml-3"></i> My Profile</a>
                <div class="dropdown-cog"></div>
                <a class="dropdown-item" href="<%= edit_user_path(current_user.id) %>">
                  <i class="fa fa-cog mr-3 ml-3"></i> Account Setting</a>
                  <div class="dropdown-divider"></div>
                  <%= link_to destroy_user_session_path,:class => 'dropdown-item', :method => :delete do %>
                  <i class="fa fa-power-off mr-3 ml-3"></i> Logout
                  <% end %>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <aside class="left-sidebar">
        <div class="scroll-sidebar">
          <nav class="sidebar-nav">
            <ul id="sidebarnav">
              <li class="sidebar-item">
                <a class="sidebar-link waves-effect waves-dark" href="<%= dashboard_path %>">
                  <i class="fa fa-dashboard"></i>
                  <span class="hide-menu">Dashboard </span>
                </a>
              </li>
              <li class="sidebar-item">
                <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                  <i class="fa fa-building-o"></i>
                  <span class="hide-menu">Store</span>
                </a>
                <ul aria-expanded="false" class="collapse  first-level">
                  <li class="sidebar-item"><a href="<%= stores_path %>" data-method="get" class="sidebar-link"><i class="fa fa-th-list"></i><span class="hide-menu"> All </span></a></li>
                  <li class="sidebar-item"><a href="<%= new_store_path %>" class="sidebar-link"><i class="fa fa-plus-circle"></i><span class="hide-menu"> New </span></a></li>
                </ul>
              </li>

              <li class="sidebar-item">
                <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                  <i class="fa fa-building-o"></i>
                  <span class="hide-menu">Validate Tickets</span>
                </a>
                <ul aria-expanded="false" class="collapse  first-level">
                  <li class="sidebar-item"><a href="<%= tickets_path %>" data-method="get" class="sidebar-link"><i class="fa fa-th-list"></i><span class="hide-menu"> All </span></a></li>
                </ul>
              </li>


              <li class="sidebar-item">
                <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                  <i class="fa fa-building-o"></i>
                  <span class="hide-menu">Customer</span>
                </a>
                <ul aria-expanded="false" class="collapse  first-level">
                  <li class="sidebar-item"><a href="<%= users_path(client:true) %>" data-method="get" class="sidebar-link"><i class="fa fa-th-list"></i><span class="hide-menu"> All </span></a></li>
                  <li class="sidebar-item"><a href="<%= new_user_path %>" class="sidebar-link"><i class="fa fa-plus-circle"></i><span class="hide-menu"> New </span></a></li>
                </ul>
              </li>



            </ul>
          </nav>
        </div>
      </aside>
      <div class="page-wrapper">
        <%= yield %>
      </div>
      <footer class="footer text-center">
        ifree
      </footer>
    </div>
  </body>
  </html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <title>Siap Aktif Lagi</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Lobster&display=swap" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <title>Hello, world!</title>
</head>
<body>

  <div class="menu-mobile-overlay bg-main d-flex flex-column justify-content-between" id="mobile-nav">

    <div class="menu-mobile-triger-close">
      <a href="javascript:void(0)" class="closebtn "  onclick="closeNav()"><i class="fa fa-times fa-2x"  style="color:#e61a58" aria-hidden="true"></i></a>
    </div>


    <img src="<%= asset_url('logo.png') %>" class="mx-auto py-4" alt="" style="width:100px;">

    <div class="w-100 py-4">

      <ul>
        <li><a href="<%= howto_path %>">Cara Bergabung</a></li>
        <li><a href="<%= tnc_path %>">Syarat dan Ketentuan</a></li>
        <li>
          <a href="#">
          <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :style => "background: #e8406b !important;color: white !important;padding: 10px 30px;border-radius: 50px;" %>
            <% else %>
            <a class="nav-link active text-center mn-btn" aria-current="page" href="<%= new_user_session_path %>" style="">Cek Poin Kamu</a>
          <% end %></a>
        </li>
      </ul>


    </div>

    <div class="py-4 menu-footer">
      <div class="row justify-content-center">
        <div class="col-4">
          <div class="my-2 text-light">
            <a href="https://www.facebook.com/ifree.indonesia/" target="_blank" class="m-2 text-light"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a href="https://www.instagram.com/ifree.indonesia" target="_blank" class="m-2 text-light"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a href="https://www.youtube.com/channel/UCB9QIR4bEn2wfiMLteLTXdQ" target="_blank" class="m-2 text-light"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
          </div>
        </div>
        <div class="d-flex w-100 justify-content-center text-light mb-3">
          <a href="<%= privacy_path %>" class="text-light mx-2"> Privacy Policy </a>
          |
          <a href="<%= tnc_path %>" class="text-light mx-2"> Terms and Condition</a>
        </div>
        <p class="text-light mb-0 text-center">Copyright iFree 2021. All rights reserved.</p>
      </div>
    </div>

  </div>

  <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top nav-top shadow-sm d-none d-md-block">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">
        <img src="<%= asset_url('logo.png') %>" alt="" style="width:100px;">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse flex-row-reverse" id="navbarNav">
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link" href="<%= howto_path %>">Cara Bergabung</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Leaderboard</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="<%= tnc_path %>">Syarat dan Ketentuan</a>
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :style => "background: #e8406b !important;color: white !important;padding: 10px 30px;border-radius: 50px;" %>
              <% else %>
              <a class="nav-link active text-center mn-btn" aria-current="page" href="<%= new_user_session_path %>" style="">Cek Poin Kamu</a>
            <% end %>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <% if @menu_homepage == true %>

  <div class="menu-mobile-triger-open d-md-none">
    <a href="javascript:void(0)" class="closebtn text-light" onclick="openNav()"><i class="fa fa-bars fa-2x" aria-hidden="true"></i></a>
  </div>

  <% else %>

  <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top  w-100 d-md-none">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">
        <img src="<%= asset_url('logo.png') %>" alt="" style="width:100px;">
      </a>
      <a href="javascript:void(0)" class="closebtn " onclick="openNav()"><i class="fa fa-bars fa-2x" style="color:#e61a58" aria-hidden="true"></i></a>

    </div>
  </nav>



  <% end %>




  <%= yield %>


  <section class="py-4 menu-footer d-md-none">
    <div class="container">
        <div class="row justify-content-center">
          <div class="col-4">
            <div class="my-2 text-light">
              <a href="https://www.facebook.com/ifree.indonesia/" target="_blank" class="m-2 text-light"><i class="fa fa-facebook" aria-hidden="true"></i></a>
              <a href="https://www.instagram.com/ifree.indonesia" target="_blank" class="m-2 text-light"><i class="fa fa-instagram" aria-hidden="true"></i></a>
              <a href="https://www.youtube.com/channel/UCB9QIR4bEn2wfiMLteLTXdQ" target="_blank" class="m-2 text-light"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
            </div>
          </div>
          <div class="d-flex w-100 justify-content-center text-light mb-3">
            <a href="<%= privacy_path %>" class="text-light mx-2"> Privacy Policy </a>
            |
            <a href="<%= tnc_path %>" class="text-light mx-2"> Terms and Condition</a>
          </div>
          <p class="text-light mb-0 text-center">Copyright iFree 2021. All rights reserved.</p>
        </div>
      </div>

  </section>

  <section class="menu-footer py-2 d-none d-md-block">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center text-light">
          <div class="">
            <a href="<%= privacy_path %>" class="text-light mx-2"> Privacy Policy </a>
            |
            <a href="<%= tnc_path %>" class="text-light mx-2"> Terms and Condition</a>
          </div>
          <div class="my-2 text-light">
            <a href="https://www.facebook.com/ifree.indonesia/" target="_blank" class="m-2 text-light"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a href="https://www.instagram.com/ifree.indonesia" target="_blank" class="m-2 text-light"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a href="https://www.youtube.com/channel/UCB9QIR4bEn2wfiMLteLTXdQ" target="_blank" class="m-2 text-light"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
          </div>
        </div>
    </div>
  </section>

<!-- <div class="position-fixed" style="bottom:5vh;right:5vh;width: 70px;">
  <a href="https://wa.me/6281285545703" class="text-center" target="_blank">
    <img src="<%= asset_url('wa.png') %>" alt="" class="w-100" >
  </a>
</div> -->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

  <!-- <script type="text/javascript">
  var imageLoader = document.getElementById('ticket_proff_of_payment');
      imageLoader.addEventListener('change', handleImage, false);

  function handleImage(e) {
      var reader = new FileReader();
      reader.onload = function (event) {

          $('.upl-trc').html( '<img class="w-100" src="'+event.target.result+'"/>' );
      }
      reader.readAsDataURL(e.target.files[0]);
  }

  </script>


  <script type="text/javascript">
  var imageLoader = document.getElementById('ticket_image_product');
      imageLoader.addEventListener('change', handleImage, false);

  function handleImage(e) {
      var reader = new FileReader();
      reader.onload = function (event) {

          $('.upl-prd').html( '<img class="w-100" src="'+event.target.result+'"/>' );
      }
      reader.readAsDataURL(e.target.files[0]);
  }

  </script> -->

  <script type="text/javascript">
    function openNav() {
  document.getElementById("mobile-nav").style.height = "100vh";
}

function closeNav() {
  document.getElementById("mobile-nav").style.height = "0";
}
  </script>

  <script type="text/javascript">
    $(window).load(function() {
    $('#popupbanner').modal('show');
});



  </script>

</body>
</html>